---
machinebox_key: ""
domain: ""
auth_uri: ""
api_uri: ""
ingress_ip: ""
ingress_fqdn: ""
version: ""
vault_version: "0.11.1"
scheme: "https"
auth_replicas: 1
api_replicas: 1
router_replicas: 1
website_replicas: 1
facebox_replicas: 1
