---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emojify-facebox
  labels:
    app: emojify-facebox
spec:
  replicas: {{.Values.facebox_replicas}}
  selector:
    matchLabels:
      app: emojify-facebox
  template:
    metadata:
      labels:
        app: emojify-facebox
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service-port": "8080"
    spec:
      containers:
      - name: emojify-facebox
        image: "machinebox/facebox"
        env:
        - name: MB_KEY
          value: "{{ .Values.machinebox_key }}"
        - name: MB_ADDRESS
          value: "127.0.0.1"
        - name: MB_PORT
          value: "8080"
